site_name: "Juan Francisco Vazquez | Portfolio & Labs"
site_description: "Portafolio profesional y documentación técnica en Redes Corporativas, Administración de Sistemas (SysAdmin) y Ciberseguridad."
site_author: "Juan Francisco Vazquez"
site_url: "https://jusnock.github.io/"

repo_name: "Jusnock/jusnock.github.io"
repo_url: "https://github.com/Jusnock"

theme:
  name: material
  custom_dir: overrides
  language: es
  logo: assets/jv_logo_minimalist.jpg
  favicon: assets/jv_logo_minimalist.jpg
  palette:
    - scheme: slate
      primary: black
      accent: cyan
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - tables
  - def_list
